version: '3'
services:
    stage_db:
        container_name: stage_db
        image: "postgres:12-alpine"
        volumes:
            - "db_vol:/var/lib/postgresql/data"
        env_file: stage.env
        networks:
            - db_net
        logging:
            driver: none
    stage_es:
        container_name: stage_es
        image: "elasticsearch:7.9.3"
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        volumes:
            - "es_vol:/usr/share/elasticsearch/data"
        networks:
            - es_net
        logging:
            driver: none
    stage_app:
        container_name: stage_app
        image: "nucleus:latest"
        env_file: stage.env
        ports:
            - "127.0.0.1:8010:5000"
        networks:
            - db_net
            - es_net
            - metrics_net
        depends_on:
            - stage_db
            - stage_es
    stage_prometheus:
        container_name: stage_prometheus
        image: prom/prometheus:v2.22.1
        volumes:
            - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
        ports:
            - "127.0.0.1:9090:9090"
        networks:
            - metrics_net
        depends_on:
            - stage_es
    stage_grafana:
        container_name: stage_grafana
        image: grafana/grafana:7.3.2
        user: "1000"
        volumes:
            - ./grafana/config.ini:/etc/grafana/grafana.ini
            - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
            - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
            - ./grafana/dashboards:/var/lib/grafana/dashboards
        ports:
            - "127.0.0.1:3000:3000"
        networks:
            - metrics_net
        depends_on:
            - stage_prometheus
networks:
    db_net:
        driver: bridge
    es_net:
        driver: bridge
    metrics_net:
        driver: bridge
volumes:
    db_vol:
    es_vol:
