version: '3'
services:
    test_db:
        container_name: test_db
        image: "postgres:alpine"
        env_file: .env
        ports:
            - "5432:5432"
        networks:
            - test_net
        logging:
            driver: none
networks:
    test_net:
        driver: bridge
