version: '3'
services:
    stage_db:
        container_name: stage_db
        image: "postgres:12-alpine"
        volumes:
            - "db_vol:/var/lib/postgresql/data"
        env_file: stage.env
        networks:
            - db_net
        logging:
            driver: none
    stage_es:
        container_name: stage_es
        image: "elasticsearch:7.9.3"
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        volumes:
            - "es_vol:/usr/share/elasticsearch/data"
        networks:
            - es_net
        logging:
            driver: none
    stage_app:
        container_name: stage_app
        image: "nucleus:latest"
        env_file: stage.env
        ports:
            - "127.0.0.1:8010:5000"
        networks:
            - db_net
            - es_net
        depends_on:
            - stage_db
            - stage_es
networks:
    db_net:
        driver: bridge
    es_net:
        driver: bridge
volumes:
    db_vol:
    es_vol:
