version: '3'
services:
    dev_db:
        container_name: dev_db
        image: "postgres:12-alpine"
        env_file: dev.env
        ports:
            - "5432:5432"
        networks:
            - dev_net
        logging:
            driver: none
networks:
    dev_net:
        driver: bridge
