version: '3'
services:
    staging_nginx:
        container_name: staging_nginx
        image: "nginx:1.18-alpine"
        volumes:
            - "./nginx/staging.nginx:/etc/nginx/conf.d/default.conf"
        ports:
            - "80:80"
        networks:
            - nginx_net
        depends_on:
            - staging_app
        logging:
            driver: none
    staging_db:
        container_name: staging_db
        image: "postgres:12-alpine"
        volumes:
            - "db_vol:/var/lib/postgresql/data"
        env_file: .env
        networks:
            - db_net
        logging:
            driver: none
    staging_es:
        container_name: staging_es
        image: "elasticsearch:7.9.3"
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        volumes:
            - "es_vol:/usr/share/elasticsearch/data"
        networks:
            - es_net
        logging:
            driver: none
    staging_app:
        container_name: staging_app
        image: "nucleus:latest"
        env_file: .env
        ports:
            - "127.0.0.1:8010:5000"
        networks:
            - nginx_net
            - db_net
            - es_net
            - metrics_net
        depends_on:
            - staging_db
            - staging_es
        restart: always
    staging_prometheus:
        container_name: staging_prometheus
        image: prom/prometheus:v2.22.2
        volumes:
            - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
        ports:
            - "127.0.0.1:9090:9090"
        networks:
            - metrics_net
        depends_on:
            - staging_es
            - staging_app
        logging:
            driver: none
    staging_grafana:
        container_name: staging_grafana
        image: grafana/grafana:7.3.3
        volumes:
            - ./grafana/config.ini:/etc/grafana/grafana.ini
            - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
            - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
            - ./grafana/dashboards:/var/lib/grafana/dashboards
        ports:
            - "127.0.0.1:3000:3000"
        networks:
            - metrics_net
        depends_on:
            - staging_app
            - staging_prometheus
        logging:
            driver: none
networks:
    nginx_net:
        driver: bridge
    db_net:
        driver: bridge
    es_net:
        driver: bridge
    metrics_net:
        driver: bridge
volumes:
    db_vol:
    es_vol:
