version: '3'
services:
    dev_db:
        container_name: dev_db
        image: "postgres:12-alpine"
        env_file: dev.env
        ports:
            - "5432:5432"
        networks:
            - db_net
        logging:
            driver: none
    dev_es:
        container_name: dev_es
        image: "elasticsearch:7.9.3"
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - es_net
        logging:
            driver: none
networks:
    db_net:
        driver: bridge
    es_net:
        driver: bridge
